name: Build and push

on:
  push:
    branches: [ main ]

env:
  DOCKER_USERNAME: nivezra

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      DOCKER_REPO_CLIENT: nivezra/super-bulb-client
      DOCKER_REPO_SERVER: nivezra/super-bulb-server
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}    

      - name: Build Docker images
        run: docker compose build
      
      - name: Bump version and push tag
        id: bump
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
      
      - name: Tag Docker images
        run: |
          docker tag $DOCKER_REPO_CLIENT:latest $DOCKER_REPO_CLIENT:${{ steps.bump.outputs.new_tag }}
          docker tag $DOCKER_REPO_SERVER:latest $DOCKER_REPO_SERVER:${{ steps.bump.outputs.new_tag }}
      
      - name: Push Docker images
        run: |
          docker push $DOCKER_REPO_CLIENT --all-tags
          docker push $DOCKER_REPO_SERVER --all-tags